export const featureFlags = {
  enableMap: true,
  enableSearchUi: true,
  enableRealRouting: true,
  enableSafetyScore: true,
  enableSafetyLayer: true,
  enableSafetySummary: true,
  enableNightMode: true,
  enableSafeRouting: true,
  enableBalancedRouting: true,
  enableNightRouting: true,
  enableRouteExplanations: true,
  enableBicimad: true,
  enableBicimadStationsLayer: true,
  enableNeighborhoodScore: false,
  enableProjectStatusPanel: true,
};
